### ISSUE TITLE
[BUG]: colour.plotting.diagrams.plot_spectral_locus overrides alpha for patch?

### ISSUE THREAD

**Issue by sobotka** [colour-science/colour#1046]
### Description

The `colour.plotting.diagrams.plot_spectral_locus` function appears to consistently override the alpha setting such that the surrounding borders fail to adopt the colours set in rcparams. This requires always following the `colour.plotting.diagrams.plot_spectral_locus` with a call to `fig.patch.set_alpha(1.0)` to repair.

Is there anything that can be done that would remove the requirement to "fix" every call?

**Comment by KelSolaar** [comment]
It is not really a bug but a default that suits the most common use case of producing a figure with transparency so that it can be embedded in a presentation, website or alike. If you pass `transparent_background=False` this should [bypass the relevant code](https://github.com/colour-science/colour/blob/c92ddd2b1e7b0e4fb76446145d47a3813890ddeb/colour/plotting/common.py#L657).
