### ISSUE TITLE
[BUG]: "colour.rgb_to_ycbcr" definition can give invalid answers for edge values.

### ISSUE THREAD

**Issue by kaihagseth** [colour-science/colour#1063]
### Description

rgb_to_ycbcr can give cb and cr values outside the defined out bit range when outputting to full range. If I feed it with 100% red the function return 1024 for the red channel, which is of course outside the range of 10 bits.

I believe that this is caused by these lines of code:
ycbcr.py:147
```python
    if is_int and not is_legal:
        ranges[3] = 2**bits
```

~~I think the fix would be just to remove these lines, but since it looks so intentional I'll leave it to the maintainer.~~ 

Actually, thinking about it again, the correct solution would be to set ranges[2] to 1.
Rec.2100, which addresses full range on page 10.
https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2100-2-201807-I!!PDF-E.pdf

Which means my suggestion is that we should make this fix:
ycbcr.py:147
```python
    if is_int and not is_legal:
        ranges[2] = 1
```

### Code for Reproduction
```python
import colour

rgb = (1.0, 0, 0)
y, cb, cr = colour.RGB_to_YCbCr(rgb, in_int=False, in_legal=False, out_bits=10, out_legal=False, out_int=True)
print(y, cb, cr)
# >> 217 395 1024
```

### Environment Information

```shell
>>> import colour; colour.utilities.describe_environment()
===============================================================================
*                                                                             *
*   Interpreter :                                                             *
*       python : 3.9.6 (default, Sep 26 2022, 11:37:49)                       *
*                [Clang 14.0.0 (clang-1400.0.29.202)]                         *
*                                                                             *
*   colour-science.org :                                                      *
*       colour : 0.4.1                                                        *
*                                                                             *
*   Runtime :                                                                 *
*       imageio : 2.22.3                                                      *
*       numpy : 1.23.4                                                        *
*       scipy : 1.9.3                                                         *
*                                                                             *
===============================================================================
defaultdict(<class 'dict'>, {'Interpreter': {'python': '3.9.6 (default, Sep 26 2022, 11:37:49) \n[Clang 14.0.0 (clang-1400.0.29.202)]'}, 'colour-science.org': {'colour': '0.4.1'}, 'Runtime': {'imageio': '2.22.3', 'numpy': '1.23.4', 'scipy': '1.9.3'}})
```

**Comment by KelSolaar** [comment]
Looking at it quickly `2**bits` seems wrong and the entire block should be removed because this case is basically handled at the start here:

```python
    else:
        ranges = np.array([0, 2**bits - 1, 0, 2**bits - 1])
```

Your proposal of assigning 1 does not really work either because under that parameterisation we would like to get the maximum code value for integer and full range, i.e. 1023 or 4095.

@nick-shaw : Do you remember why you added that if statement, it is so specific that you might have had a good reason.

The JFIF JPEG dockets blows with the correction:

```python
File "/Users/kelsolaar/Documents/Development/colour-science/colour/colour/models/rgb/ycbcr.py", line 436, in ycbcr.RGB_to_YCbCr
Failed example:
    RGB_to_YCbCr(
        RGB,
        K=WEIGHTS_YCBCR["ITU-R BT.601"],
        in_bits=8,
        in_int=True,
        out_legal=False,
        out_int=True,
    )
    # doctest: +ELLIPSIS
Expected:
    array([ 36, 136, 175]...)
Got:
    array([ 36, 136, 174])
```

**Comment by kaihagseth** [comment]
The reason why 1 is added as the minimum value to the C-values is that they should be symmetric around 0 in a signed world. So for an 10 bit signed case, the valid signed values would be -511 to 511, or in unsigned terms: 1 to 1023, centered around 512, which is achromatic...

We would still get the max value for integer full range of course, since the max value is not touched. Note that I changed the index from 3 to 2, to address the min value instead of the max value, since that, as you mentioned, is handled in the case above.

I suspect that the original author wanted to have the correct middle point (512 in the 10 bit example), and that is why they went from 0-1024. But that won't work of course, since that is outside the 10 bit range... So setting the c min value to 1 is the solution that works for both these cases...

**Comment by nick-shaw** [comment]
There is a note about the JFIF conversion and the 256 issue in the code [here](https://github.com/colour-science/colour/blob/d0152dcc9e49f912bd116b502aee613dc91c486c/colour/models/rgb/ycbcr.py#L427).

But thinking about it, perhaps the range should be set to 0.5 to 255.5, for 8-bit, rather than 0 to 256. That would center on 128 as per the spec, and I think more accurately match e.g. `128 + 255 * Cr` where Cr is ranged -0.5 to 0.5. Because of the  "add 0.5 and truncate" rounding method, this will produce output ranged 1-256. But that would seem to match the spec. It does seem odd not to have used `127 + 255 * Cr` which would have ranged 0-255 after adding 0.5 and truncating. But it is not for us to judge or modify the spec. We just implement it!

The fact that an output value of 256 can be produced is intentional. Colour never clamps values, because it does not limit its output. It is for users of the library to clamp (or not, as appropriate) the results in their own code.

The point about the rounding method used by `np.round` is a good one. Maybe the code should be changed to simply use `int(x + 0.5)` as is used in specs. Or perhaps the extended version from BT.2100:
`Round( x ) = Sign( x ) * Floor( | x | + 0.5 )`.

**Comment by kaihagseth** [comment]
As you mentioned, the range of outputs of the function in JFIF actually becomes 1-255, since the spec specifies that the value is clamped between 0 and 255, and that the inputs only can yield answers between 1 and 256 before clamping. The BT.2100 spec also specifies that the legal range for full range ycbcr is from 1 to (2**bits)-1. (which in that case in 10/12 bits.)

I have a feeling that just changing the range to 1 to (2**bits)-1 will yield correct answers for all inputs in both these cases, but that should be tested. 

Giving pure red blue or pure red as in input to a rgb_to_ycbcr-function does not seem that crazy either, both are probably in the top 5 use cases for this function when using full range output. (Does 100% yellow and cyan also fall within this edge case?) I also think that the spec the math and rounding it does specifically to get a symmetric output around (2**bits)/2 from 1 to (2**bits)-1, so implementing the kind of wonky math without the clamping will give unintentonal results. 

You say that the only user of full range YCbCr is JFIF, but BT.2100 also opens for this for HDR broadcast and production.

I think that users will expect a function where you specify "output=10bits", and input a value within the legal input range will actually output a value that fits in 10 bits, but maybe that is just me.

**Comment by nick-shaw** [comment]
I have been experimenting with a [modification](https://github.com/nick-shaw/colour/blob/experimental/jfif-alt/colour/models/rgb/ycbcr.py) which I think now accurately reflects the intent of ITU-T T.871.

You are right that BT.2100 also defines full range Y'CbCr. I had forgotten that. The quantisation function would appear to match that of ITU-T T.871, but defined for arbitrary bit depth *n*. I think my modified code is still therefore correct for this. I have also added a `clamp_int` argument, defaulting to `True` which clamps to the possible range for `bit_depth` integers. SDI reserved code value handling as mentioned in BT.2100 is "application specific" and would need to be dealt with in application specific code.

I am not confident that changing the range to 1 to (2\*\*bits)-1 would yield correct answers in all cases. I have not tested either, but it feels intuitively as if there may be cases where the rounding would go in a different direction for some code values. 0.5 to 2\*\*bits - 0.5 exactly matches the spec.

**Comment by KelSolaar** [comment]
Thank you @nick-shaw!
