### ISSUE TITLE
CRI Incorrect Labels in Plot 

### ISSUE THREAD

**Issue by blue-j** [colour-science/colour#1175]
### Description

It looks like instead of “Ra”, “R1”, etc, the default labels in CRI plotting use the “Qa”, “Q1”, labels. I reserve the right to be wrong!  - J

### Code for Reproduction

from colour import SDS_ILLUMINANTS
illuminant = SDS_ILLUMINANTS["FL2"]
plot_single_sd_colour_rendering_index_bars(illuminant)

**Comment by KelSolaar** [comment]
It is because both the _colour quality scale_ and _colour rendering index_ use the same underlying definition. I did not really bothered changing the labels as there is no standard diagram defined for them and they both return a measure of colour quality, hence the `Qn` labelling. We could change it to have a specific labelling per-method that said.
