### ISSUE TITLE
[BUG]: `cmfs` argument are not porperly used in `plot_RGB_colourspaces_in_chromaticity_diagram_CIE1931`

### ISSUE THREAD

**Issue by Globefishp** [colour-science/colour#1314]
### Description

In the document, `cmfs` argument is used to calculate the spectra locus in chromaticity diagram. But I found in `plot_RGB_colourspaces_in_chromaticity_diagram_CIE1931` this argument are not used, it always produce a result based on CIE1931-2 deg observer. While `plot_chromaticity_diagram_CIE1931`, `plot_chromaticity_diagram`, `plot_spectral_locus` all works well, I think the `cmfs` may be not porperly passed.

### Code for Reproduction

```python
import colour
from colour.plotting import *

colour.plotting.diagrams.plot_spectral_locus(
    cmfs='CIE 2015 2 Degree Standard Observer'
)
colour.plotting.diagrams.plot_chromaticity_diagram(
    cmfs='CIE 2015 2 Degree Standard Observer'
)
colour.plotting.diagrams.plot_chromaticity_diagram_CIE1931(
    cmfs='CIE 2015 2 Degree Standard Observer'
)
colour.plotting.plot_RGB_colourspaces_in_chromaticity_diagram_CIE1931(
    ['sRGB'],
    cmfs='CIE 2015 2 Degree Standard Observer'
)
```

**Comment by KelSolaar** [comment]
Hi @Globefishp,

This is by design, the `colour.plotting.plot_RGB_colourspaces_in_chromaticity_diagram_CIE1931` definition does use and enforce the *CIE 1931 2 Degree Standard Observer* for its computations.

More specifically, the transformation from *CIE XYZ Tristimulus Values* to *Chromaticity Coordinates xy*. This not only cannot be changed but most of the *RGB* colourspaces are defined for the *CIE 1931 2 Degree Standard Observer*. 

Hope this helps,

Cheers,

Thomas
