### ISSUE TITLE
Add MacAdam ellipses plotting example.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#18]
## References
- Macadam, D. L. (1942). Visual Sensitivities to Color Differences in Daylight. Journal of the Optical Society of America, 32(5), 247. doi:10.1364/JOSA.32.000247
- https://sites.google.com/site/malscolourscience/macadam

**Comment by nschloe** [comment]
I'm currently trying to get MacAdams ellipses plotted in [colorio](https://github.com/nschloe/colorio), but I'm somewhat at loss on how to interpret the data in [the original paper](https://doi.org/10.1364/JOSA.32.000247). Table 3 therein gives the ellipse data, but when plotting the x-y locations of the filter pairs, their connecting lines, and the average theta settings, I'm getting all but a coherent image from which one can deduce an ellipse:

![ma](https://user-images.githubusercontent.com/181628/36757226-56754000-1c11-11e8-9b4a-7ee5ca9f34b2.png)

How does everyone draw those at all?

**Comment by KelSolaar** [comment]
I have never looked at that beyond saying would be great to have :)

**Comment by nschloe** [comment]
Got it:

![d](https://user-images.githubusercontent.com/181628/36788224-5bf1ecd2-1c8d-11e8-8ec7-e59bafc54b3c.png)

Turns out that you have to use the `delta y/delta x` and `delta s` data (plus a curve fit) to reproduce the ellipses. I still have no idea how to correlate this with the actual measurements, but I guess that goes to show that you'll have to be very cautious when using MacAdam data for any quantitative studies.

**Comment by KelSolaar** [comment]
Nice! PR Welcome ;)

**Comment by iinnovations** [comment]
You’re going to have to parametrize these so that you can feed them into a geometry point in feature function anyway. I’ve done this in other languages and will run into this shortly here in python. I’ll send a PR when I get to it. 

C

**Comment by KelSolaar** [comment]
Thanks Colin (@iinnovations)!

**Comment by vvclin-git** [comment]
You can calculate MacAdam ellipse using FMC equations.
https://www.osapublishing.org/josa/abstract.cfm?uri=josa-61-1-118
