### ISSUE TITLE
No "ACEScg" <---> "scene linear" transforms available.

### ISSUE THREAD

**Issue by zachlewis** [colour-science/colour#218]
Hey there,

I noticed that the transforms provided under the ACEScg colorspace are actually using the ACESproxy transforms; from my understanding, ACESproxy is much more akin to ACEScc, but with a gamut limited to values that can be represented over SDI. 

Would it make more sense to provide ACEScg transforms that, more or less, convert from scene linear with rec709 primaries to AP1 primaries, and back? (And would that, indeed, be the correct transform to use? I'm still learning this stuff).

Defaulting to ACESproxy transforms seems... perhaps dangerously incorrect. Unless I'm missing something, which is entirely possible.

Thanks!

**Comment by KelSolaar** [comment]
Hi Zach,

> Defaulting to ACESproxy transforms seems... perhaps dangerously incorrect.

It is erroneous indeed and should have been fixed in [feature/v0.3.7](https://github.com/colour-science/colour/tree/feature/v0.3.7/) branch as per S-2014-004 <sup>[1](#foot_note_1)</sup> in #216.

- <a name="foot_note_1">1</a>: The Academy of Motion Picture Arts and Sciences, Science and Technology Council, & Academy Color Encoding System (ACES) Project Subcommittee. (2015). Specification S-2014-004 - ACEScg – A Working Space for CGI Render and Compositing, 1–9. Retrieved from https://github.com/ampas/aces-dev/tree/master/documents

**Comment by bxyldy** [comment]
Awesome! Thanks so much. Really appreciate the work you guys have put into this.

**Comment by KelSolaar** [comment]
You are welcome! :)
