### ISSUE TITLE
Why not use the "cmfs" parameter for the "XYZ" conversion in the "spds_CIE_*_chromaticity_diagram_plot" functions?

### ISSUE THREAD

**Issue by henczati** [colour-science/colour#221]
In `colour/plotting/diagrams.py`, `spds_CIE_*_chromaticity_diagram_plot` functions.

**Comment by KelSolaar** [comment]
I'm somehow right now enforcing *CIE 1931 2 Degree Standard Observer* usage because there are still fundamental questions I don't have any answers to, the main ones being: The RGB colourspaces we are using (*sRGB*, *ACES2065-1*, *Rec. 2020*) have been defined using the *CIE 1931 2 Degree Standard Observer* but what happens to their primaries / whitepoint when you use a different observer? Should you update those primaries? How do you do that?

This is related to #25.
