### ISSUE TITLE
Implement support for "Y'CbCr" colourspace.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#252]
References
---------------

- https://en.wikipedia.org/wiki/YCbCr

**Comment by Nick-Shaw** [comment]
Worth reading http://major-kong.blogspot.co.uk/2013/12/the-best-of-times-worst-of-times.html regarding Y'CbCr.

As that article points out, there are a number of different implementations out there which give varying results for Y'CbCr <> R'B'G' conversion, even though the maths is given in detail in the Rec.709 documentation – https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.709-6-201506-I!!PDF-E.pdf

**Comment by KelSolaar** [comment]
Thanks Nick! I read that article a while back. I haven't yet deeply thought up to where we will implement that. A first clear thing though is that I would be able to rotate from *R'G'B'* to *Y'CbCr* and vice-versa.

**Comment by sobotka** [comment]
Could be a nightmare given that YCbCr encoding schemes rely on luminance weights per set of RGB primaries, as well as the jungle of ranges that are acceptable. Broadcast (Y 16-235, Cb / Cr 16-240), Broadcast full (1-254), DSLR nonstandard full (0-255) etc.

**Comment by KelSolaar** [comment]
@sobotka: Yeah it is a tricky beast to tackle, I have it since a while on my TODO list but it was quite low in the priority stack (and still is), but as I came across the need to play with that, it deserved a proper issue. @Nick-Shaw sent me some code, I'll take a look at that whenever I have some time to allocate for it.

**Comment by Nick-Shaw** [comment]
My code was fairly basic. It only did the Rec.709 colour space, and had three versions which produced either float Y'PbPr, legally ranged float Y'CbCr, or n-bit integer legally ranged Y'CbCr.

As an exercise in coding I will try and find time to write an improved version, with more options. Because there are so many permutations, it may be better to parameterise everything, so you give it Kr, Kb, Ylow, Yhigh, Clow, Chigh, RGBlow, RGBhigh to define the primaries and ranges. And maybe create some presets for common options.

**Comment by KevinJW** [comment]
Don't forget constant vs non-constant luminance mostly needed for Rec 2020. I agree the parameterisation by Kr/Kb makes most sense, not sure about the scaling options being part of the conversion, they are typically part of a specific encoding, e.g. 8 bit digital video, and naive scaling to other bit depths is incorrect [digital video interface scaling is (255 * 2^(bits - 8))].

Kevin

**Comment by Nick-Shaw** [comment]
Been looking at it today actually. I ignored the Rec.2020 constant luminance version for now, as I wasn't sure how best to implement that. Because the transform uses linear Y and gamma coded R'G'B' it means the gamma conversion probably needs to be incorporated into the rgb_to_YcCbcCrc(rgb) function. I think therefore this should be a separate function from the rgb_to_YCbCr(rgb) function I have already written.

I feel the parameterisation of the ranges that I have implemented works for me, but others may disagree.

My knowledge of how GitHub works is not good enough that I feel ready to post code directly just yet! I was planning to send what I have done to @KelSolaar later today. I will send it to you as well @KevinJW. If anybody else wants to take a look, let me know.

Nick

**Comment by Nick-Shaw** [comment]
You are right, @KevinJW,  that naive scaling between float representations of integer coding will yield incorrect results, because 16.0/255.0 != 64.0/1023.0.

My code gets round this by letting you pass arguments in the following way:
>>>YCbCr = rgb_to_YCbCr(rgb,  inRange=[16.0/255, 235.0/255], outRangeY=[64, 940], outRangeC=[64, 960])

The above line tells the transform that the input R'G'B' values are floating point, derived as fractions of 255 from an 8-bit legally ranged source, and the function should return the Y'CbCr values using 10-bit integer code values.

The function will assume Rec.709 luma weightings unless you specify otherwise, by passing it e.g. K=[0.299, 0.114] for Rec.601.
