### ISSUE TITLE
Add various camera spectral sensitivities.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#255]
## References
- https://spectralestimation.wordpress.com/data/

As part of #192, it would be great to also add various camera spectral responses.

**Comment by scooperly** [comment]
This seems like a good point to bring up to Alex Forsythe or Scott Dyer on the ACES team, since they had to acquire spectral data to produce IDTs. I'm not so sure how the companies would feel about releasing the data publicly, but worth a shot :)

Also there have been a number of studies that required measuring spec. sens. for consumer cameras like ( https://www.cis.rit.edu/people/faculty/jwgu/research/camspec/camspec.pdf ) Data could be available from these sources as well.

**Comment by KelSolaar** [comment]
That would be great indeed! A long term goal would be to implement support for their characterisation too, this is also somehow related to #63.

Jinyu Fang (@fangjy88) had planned to contribute some related code, I'm not sure what is the latest on that one.

**Comment by Nick-Shaw** [comment]
I'm not sure that the ACES team produced any of the IDTs themselves. I think they deliberately left it up to the camera manufacturers to create them. Indeed the IDT folder in the ACES repository is called "vendorSupplied", which would support this.

**Comment by KelSolaar** [comment]
@Nick-Shaw : Yeah but they may have access to some spectral data, Jim Houston kindly gave me the [Kinoton spd](https://github.com/colour-science/colour/blob/develop/colour/colorimetry/dataset/light_sources/spds.py) for example. I'm summoning @alexfry here :)
