### ISSUE TITLE
Investigate correctness of "REDLogFilm" and "ViperLog" log encoding functions.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#260]
I just stumbled upon this:

![image](https://cloud.githubusercontent.com/assets/99779/13726330/a1e083ac-e927-11e5-8bf4-5cfa8adc7253.png)

The *REDLogFilm* and *ViperLog* log encoding functions roll off at 1.0 which seems inconsistent.

**Comment by Nick-Shaw** [comment]
I haven't double-checked, but I think you may be using the legacy REDlog function, not REDlogFilm. REDlog does only code the 0-1 range, as it codes sensor data normalised to the 0-1 range. REDlogFilm is the Cineon function as used in Nuke, i.e.:
    REDlogFilm(lin) = (math.log10(lin*0.9892 + 0.0108)*300.0 + 685.0)/1023.0

**Comment by Nick-Shaw** [comment]
I had to dig back and find a Shake macro I wrote in 2009 to find the REDlog transfer function. It does look like that is what you are using. REDlogFilm superceded REDlog in 2010 with the introduction of RED's "FLUT Color Science" and was designed to be Cineon compatible as Cineon is implemented in Shake and Nuke. Prior to that, RED's image processing was fundamentally 12-bit integer, with REDlog used as a way of coding the 12-bit linear A/D values as 10-bit.

**Comment by Nick-Shaw** [comment]
ViperLog works similarly to REDlog, and also only codes 0-1. I just noticed that the original REDlog is still included in the Nuke root "LUTs" and I'm guessing this is where the REDlogFilm function in Colour came from.

So to be clear, REDlog != REDlogFilm

**Comment by KelSolaar** [comment]
Thanks for taking a look at that @Nick-Shaw! `REDlogFilm` name is likely an error on my end when I ported the functions from https://github.com/imageworks/OpenColorIO-Configs/blob/master/nuke-default/make.py.

So this is an actual defect, but it also means that I'll have to dig a proper curve for REDlog, I'll check what we have in the ACES 1.0 OCIO configurations.

**Comment by Nick-Shaw** [comment]
Yes, that OCIO script creates LUTs for the Nuke Default set of curves, which includes legacy REDlog, but does not have a separate entry for REDlogFilm, because the Cineon entry already covers it.

**Comment by Nick-Shaw** [comment]
You'll see that https://github.com/hpd/OpenColorIO-Configs/blob/master/aces_1.0.1/python/aces_ocio/colorspaces/red.py defines REDlogFilm as being the same as Cineon. I suggest you should do the same, rather than defining it separately as the same function.

The curve you have as REDlogFilm is the correct curve for REDlog, just incorrectly named. Frankly nobody should be using REDlog any more. It's only still about for historical completeness.

A couple of fairly straightforward corrections to models/rgb/conversion_functions/log.py and models/rgb/dataset/red.py should be all that is needed to fix this.

**Comment by KelSolaar** [comment]
Thanks @Nick-Shaw, it should be fixed now. :)
