### ISSUE TITLE
Fix and improve "Sony S-Log" curves implementation errors and consistency.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#336]
@Nick-Shaw spotted some inconsistencies in our *Sony S-Log* curves implementation that we should address.

**Comment by Nick-Shaw** [comment]
It's more than inconsistencies. The documents referenced were written before S-Log2 existed yet the formula used for S-Log2 is for some reason drawn from those documents.

1. S-Log2 is missing altogether, with the formula used for S-Log2 actually being S-Log1.

2. The S-Log1 and S-Log3 functions are inconsistent because S-Log1 expects "linear IRE" (a term I've only seen in Sony documents) as input, whereas S-Log3 expects linear reflectance.

3. S-Log1 output is related to IRE, i.e. 1.0 output means CV 940, whereas for S-Log3 1.0 output means CV 1023.

4. A linear portion below zero was added to the S-Log1 curve at a later data than the documents referenced (possibly when S-Log2 was created) and this is not included in the functions.

The ACES IDTs are a good reference for the correct functions. They include the 0.9 IRE to reflectance factor, and full to legal scaling where needed.

Because S-Log1 and 2 are defined relative to IRE (Sony obviously gave up on this with S-Log3) there are two versions of their IDTs, for 10 and 12 bit. We could generalise this by adding a `bit_depth=n` kwarg if we wanted to be fully accurate.

**Comment by KelSolaar** [comment]
Thanks @Nick-Shaw! Taken a quick look I'm actually not sure where the S-Log2 function is coming from. I'll try to investigate further as it is puzzling me.
