### ISSUE TITLE
Re-include "setup.py" file in distribution.

### ISSUE THREAD

**Issue by MarcusCalhoun-Lopez** [colour-science/colour#546]
I maintain [Colour](https://github.com/macports/macports-ports/blob/master/python/py-colour/Portfile) for the [MacPorts](https://www.macports.org) project. 
The Python installation framework for MacPorts is built around the existence of setup.py. 
As of Colour 0.3.14, however, setup.py no longer exists in the downloadable release file. 
Can setup.py be restored? 
Thank you.

**Comment by KelSolaar** [comment]
Hi @MarcusCalhoun-Lopez,

Thanks, so this should be fixed in the future 0.3.15. We adopted [Poetry](https://poetry.eustace.io/) during 0.3.14 and as a consequence, we did not really need the `setup.py` file anymore, so 0.3.14 was released without it. However, it turns out that a few processes are requiring it, e.g. Github dependencies tracking, etc... Thus we have reinstated it!

Cheers,

Thomas

**Comment by MarcusCalhoun-Lopez** [comment]
Thank you very much for the information.

-Marcus

**Comment by KelSolaar** [comment]
You are welcome. BTW, thanks a lot for managing the MacPorts version of Colour!
