### ISSUE TITLE
Investigate "Bokeh".

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#62]
## References
- http://bokeh.pydata.org/

**Comment by canavandl** [comment]
I've been playing around with Bokeh to implement the CIE 1931 Chromaticity Diagram, using the colour/colour/plotting/resources pngs. Do you know why the 1931 CIE Chromaticity/1931 2 Deg Observation pngs (I didn't check the others), have aspect ratios not quite equal to one? It's close (~1.04% for the Small i.e. 992x1024), but when using Bokeh's figure.image_url (similar to matplotlib's imread) and scaling the x and y to (0,1), the height is always a pixel longer than the width (which is a bug on their part). Because they use the upper left corner as the origin (as opposed to matplotlib's lower left), they pixel hangs over the x axis.

I'll submit a bug report of Bokeh and see what they say, but I'm curious about the origin of the CIE chromaticity images Colour is using and why they don't quite have an aspect ratio of one.

**Comment by KelSolaar** [comment]
The images have been generated through brute force plotting with matplotlib using definitions such as this one: https://github.com/colour-science/colour/blob/develop/colour/plotting/diagrams.py#L68

The ratio is the one defined by matplotlib when I remove all the jazz around the figure (margins, tickers, etc...), I don't know why the figure is not square even though I input square dimensions. Interestingly it seems to reload fine and is aligned properly. I noticed there is a black line actually in the images on the left if I recall correctly, I need to investigate it.

**Comment by canavandl** [comment]
The images scale and align correctly using Colour (via matplotlib) for me too. I was also able to read the image in using matplotlib's image.imread (as a RGBA NxMx4 array), convert it to a NxM uint32 array (the input type for Bokeh's image_rgba method) and have that correctly scale. Obviously, this is slow and requires matplotlib. It's just Bokeh's current image_url method (passing the filename) that doesn't scale the image correctly.

Here's the issue I submitted to the Bokeh tracker: https://github.com/bokeh/bokeh/issues/2127

**Comment by KelSolaar** [comment]
Just a head up on this one Luke, I have re-rendered the images in the [feature/vectorise](https://github.com/colour-science/colour/tree/feature/vectorise) branch and they should have a 1:1 aspect ratio now.

Thomas
