### ISSUE TITLE
Transfer function for "ICtCp" should vary with method (PQ / HLG)

### ISSUE THREAD

**Issue by nick-shaw** [colour-science/colour#764]
https://github.com/colour-science/colour/blob/02b595b26313c4b4f55adc41d599f90c4c9edbcd/colour/models/rgb/ictcp.py#L192
This appears always to use `eotf_inverse_ST2084` but should in fact use `oetf_HLG_BT2100` if `method` is `'ITU-R BT.2100-2 HLG'`, according to the November 2020 revision of Rec. ITU-R BT.2100-2.

**Comment by KelSolaar** [comment]
Ah good point, I forgot to add that!

**Comment by KelSolaar** [comment]
So yeah, re-reading that properly, at least with the previous tables, it makes sense. I wish they used subscripts to the OETF and EOTF functions in the formulas.

**Comment by KelSolaar** [comment]
Complexity raises quite significantly because we need to support the two HLG EOTFs:

- BT.2100-1
  - PQ EOTF & PQ Matrix
  -  HLG-1 EOTF & PQ Matrix

- BT.2100-2
  - PQ EOTF & PQ Matrix
  -  HLG-2 EOTF & HLG-2 Matrix

We also need to pass `kwargs` to the HLG EOTFs.

**Comment by nick-shaw** [comment]
It’s the HLG OETF, not the EOTF, so there are no kwargs. But it’s still a lot of permutations.

**Comment by KelSolaar** [comment]
Yes!

**Comment by nick-shaw** [comment]
I think this should do it:
```python
    RGB = to_domain_1(RGB)

    LMS = vector_dot(MATRIX_ICTCP_RGB_TO_LMS, RGB)

    with domain_range_scale('ignore'):
        LMS_p = (oetf_HLG_BT2100(LMS) if 'hlg' in method.lower()
                 else eotf_inverse_ST2084(LMS, L_p))

    ICtCp = (vector_dot(MATRIX_ICTCP_LMS_P_TO_ICTCP_HLG_BT2100_2, LMS_p)
             if method.lower() == 'itu-r bt.2100-2 hlg' else vector_dot(
                 MATRIX_ICTCP_LMS_P_TO_ICTCP, LMS_p))

    return from_range_1(ICtCp)
```
Note the lower case 'itu-r bt.2100-2 hlg', where the 'ITU-R BT.2100-2 PQ' is currently (incorrectly, I believe) in caps.

**Comment by ValZapod** [comment]
IMHO, duplicated matrix in BT.2100-1 for HLG was just a a bad typo, because the derivation of ICtCp matrix from IPT matrix must be different, so no need for all this duplications.

The following is all from https://professional.dolby.com/siteassets/pdfs/ictcp_dolbywhitepaper_v071.pdf

"The transformation from ITU-R BT.2020 primaries [1] into ICTCP using the PQ ST 2084 [2] non-linearity is given below. ICTCP has also been defined utilizing the HLG non-linearity, but that derivation will not be discussed in this paper. Minimal testing utilizing the HLG non-linearity has been completed assuming a 1000 cd/m2 display. Relative results are comparable."

_To LMS_ matrix is obviously the same and is matrix from original https://en.wikipedia.org/wiki/LMS_color_space#Hunt,_RLAB matrix used to derive IPT 1998 but with higher precision, as specified here http://brucelindbloom.com/index.html?Eqn_ChromAdapt.html (only 0.4002400 matters practically speaking, you use it). Now multiply with 0.04 crosstalk invert XYZ to BT.2020 matrix to get BT.2020 RGB to LMS.

Now with second PQ matrix from nonlinear L'M'S' it is more complex stuff: using 1998 IPT matrix you apply a rotation matrix of 1.134464 radians and then apply a scalar to **fit chroma between -0.5 and +0.5.**

HLG second matrix derivation is to be found.

**Comment by nick-shaw** [comment]
It may have been incorrect, but it existed in a published version of the paper. What we try to do with Colour is enable people to match any other implementation, current or historical. If somebody needed to match the processing in an application version released while the old matrix was published, they would need that option.

**Comment by KelSolaar** [comment]
> What we try to do with Colour is enable people to match any other implementation, current or historical. If somebody needed to match the processing in an application version released while the old matrix was published, they would need that option.

Yes! :)
