### ISSUE TITLE
Implement parser for "Sekonic" and "UPRTek" CSV files.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#796]
References
---
- [RANDOM_001_02°_3262K.csv.txt](https://github.com/colour-science/colour/files/6139892/RANDOM_001_02._3262K.csv.txt)
- [ESPD2021_0104_231446.xls.txt](https://github.com/colour-science/colour/files/6248058/ESPD2021_0104_231446.xls.txt)

**Comment by SGeetansh** [comment]
Hey @KelSolaar 
I would like to work on this. Will you please guide me on what information and in what format is required? It will be appreciated if you could give me an example.

**Comment by KelSolaar** [comment]
Hi @SGeetansh,

We would ideally get a `colour.SpectralDistribution` out of it. I was thinking we could actually subclass `colour.SpectralDistribution_IESTM2714` directly and shove whatever extra metadata in a new attribute for that sub-class.

I know that @JGoldstone has used it for personal stuff, maybe he can comment on what he ended up doing for the extra metadata he needs to carry?

Cheers,

Thomas

**Comment by JGoldstone** [comment]
I didn’t finish the work but yeah, I was going exactly for an IES TM 27 14-based result.

As for how to carry the extra info, that’s a great question. I see two ways and I don’t have the ability to read the spec and find out which is more likely to foster interoperability across applications. The first way is to subclass and add more elements. The second is to not exceed the set of elements implemented in tm2714.py, and to JSON-encode additional metadata in the Comments element of the header.

I took the former path recently for colorimetry. New stuff in red.

<IESTM2714 xmlns="http://www.arri.de/camera" version="0.1">
  <Header>
    <Manufacturer>Epic Games, Brompton, ROE Visual</Manufacturer>
    <CatalogNumber>Unreal Engine 4.26.1, SX40+XD, Black Pearl 2.6mm</CatalogNumber>
    <Description>LED wall color cube corners</Description>
    <DocumentCreator>jgoldstone</DocumentCreator>
    <UniqueIdentifier>Pikachu.local_2021-03-17T17:28:28</UniqueIdentifier>
    <MeasurementEquipment>cs2000</MeasurementEquipment>
    <Laboratory>ARRI Burbank MRPS</Laboratory>
    <ReportNumber>cli_tools</ReportNumber>
    <ReportDate>2021-03-17T17:28:28</ReportDate>
    <DocumentCreationDate>N/A</DocumentCreationDate>
    <Comments>N/A</Comments>
  </Header>
  <ColorimetricQuantity>radiance</ColorimetricQuantity>
  <Origin>measured</Origin>
  <ReflectionGeometry>N/A</ReflectionGeometry>
  <TransmissionGeometry>N/A</TransmissionGeometry>
  <BandwidthFWHM>N/A</BandwidthFWHM>
  <BandwidthCorrected>False</BandwidthCorrected>
  <Colorimetry>
    <Observer>CIE 1931 2 Degree Standard Observer</Observer>
    <ColorSpaceModel>CIE XYZ</ColorSpaceModel>
    <ComponentValue Label="X">0.4397119858969664</ComponentValue>
    <ComponentValue Label="Y">0.4898548339020832</ComponentValue>
    <ComponentValue Label="Z">0.06597206712062083</ComponentValue>
    <ReferenceWhite>N/A</ReferenceWhite>
  </Colorimetry>
</IESTM2714>

Thomas, as you’ve said, the ultimate way to carry around measurements would be CxF; yet it is a monster of a spec.

How many files of the above format do I have, and is that number so large that I have compatibility constraints? The answer is: 3. Yes, I only have three .colx files that I care about, as the code was written Monday of last week and used for three LED wall measurements Wednesday.

Maybe there is a middle ground where instead of just winging it, as I did with the above attributes, I could look at the name CxF uses for comparable semantic entities and use those; and if there are more we want to add, we follow that tactic whenever possible. Were we to do that, then when we did have a CxF implementation, transcoding from existing .spdx (and my .colx) measurements to CxF measurements might be easier.

I guess I should clean this up by renaming that outer tag to ColorimetryExtensionToIESTM2714...

Best—
—joseph

**Comment by SGeetansh** [comment]
Sorry got caught up with some college stuff. I got to the issue yesterday and have a confusion. In the sample CSV file given above, I think we have 2 types of spectral data, both uniformly spaced, but the first one by a difference of 5 and the second one by a difference of 1. I compared the values and noticed they are different. Which one do we want?

**Comment by KelSolaar** [comment]
No worries! Great question between the 5nm and the 1nm, the UPRTek file format is almost a copy-cat of this one and uses 1nm only. Not that this is interpolated data though. I will try to source a sample file tomorrow.

For the Sekonic, I was about to suggest that we layer the two datasets on top of each other to see the difference between the two variants. Interestingly enough, if you look at the values between the two sets, e.g. 555nm, they are different:

- 0.000405657454
- 0.000405925355

**Comment by SGeetansh** [comment]
Yeah, the values are different. I will be waiting for the sample file :)

**Comment by KelSolaar** [comment]
@SGeetansh : UPRTek file attached in OP!

**Comment by SGeetansh** [comment]
@KelSolaar 
The CSV file that we get from Sekonic or UPRTek, is that in a set template or can that vary? Depending on that, I have implemented both the hardcoded solution and the flexible one (in case there isn't a set template). The flexible one is commented for now. I have implemented both the solutions for both Sekonic and UPRTek.

Here's the permalink for the Sekonic parser
https://github.com/SGeetansh/colour/blob/89c32ed45258b35d69a374dd375bbffb51e3c6b3/colour/io/sekonic.py#L20

**Comment by KelSolaar** [comment]
Thanks @SGeetansh! Ideally here we would have a parser that is much more flexible I reckon, i.e. without hardcoded offsets. It would also be great to pull down the other defined attributes.

**Comment by SGeetansh** [comment]
@KelSolaar Sure Thomas, I will use the commented code then. How should I treat the leftover metadata?

**Comment by KelSolaar** [comment]
As discussed above, I think we could try to use `colour.SpectralDistribution_IESTM2714` to see what can be slotted in natively.

**Comment by SGeetansh** [comment]
I was working on this issue yesterday and this is where I am a little guidance.

I planned to subclass `SpectralDistribution_IESTM2714` and check the already defined attributes, compare those to what we have in the sekonic and UPRTek CSV, and examine what can be slotted in natively. Whatever extra attributes were present, I planned to write new code for them. Or I could just put them together in a JSON file as done by @JGoldstone.

Being a newbie, maybe I am a little confused with the names but what I found was that there were no common attributes/properties in CSV and the SpectralDistribution_IESTM2714 class. Out of the two methods that we have in SpectralDistribution_IESTM2714 (`read` and `write`), I will be using my code for the `read` method. Since there were no common attributes, why are we really using it as the parent class?

**Comment by KelSolaar** [comment]
> I will be using my code for the read method. Since there were no common attributes, why are we really using it as the parent class?

You get write for free and in a standard way! It is not big deal if there are no attribute in common and yeah, we can encode all of them as JSON in the comments.
