### ISSUE TITLE
Using convert with sRGB sources resets the domain-range scale to 'reference'

### ISSUE THREAD

**Issue by whornsby** [colour-science/colour#838]
Example with HSV:

```python
>> colour.set_domain_range_scale('1')
>>> colour.get_domain_range_scale()
'1'

>>> colour.convert([0,1,0],'sRGB','HSV')
array([ 0.33333532,  1.        ,  1.00004032])

>>> colour.get_domain_range_scale()
'reference'
```

Example with CIE Lab:

```python
>>> colour.convert([1,0,0],'sRGB','CIE Lab')
array([ 0.53232882,  0.80111178,  0.67223704])

>>> colour.get_domain_range_scale()
'reference'
```

This doesn't really affect the conversion, as it's noted [in the documentation](https://colour.readthedocs.io/en/latest/generated/colour.convert.html) that the domain-range scale is forced to 1, but since it changes the domain-range scale globally, you can easily run into problems:

```python
>>> colour.set_domain_range_scale('1')
>>> red = colour.convert([1,0,0],'sRGB','CIE Lab')
>>> yellow = colour.convert([1,1,0],'sRGB','CIE Lab')
>>> colour.delta_E(red,yellow)  
1.550188690276922  # a very wrong answer

>>> colour.get_domain_range_scale()
'reference'

>>> colour.set_domain_range_scale('1')
>>> colour.delta_E(red,yellow)
64.306528723019156  # the correct answer
```

Side note: I think whoever last updated the documentation jinxed themselves when they added this warning:

> The domain-range scale is ‘1’ and cannot be changed.

*if only...*

**Comment by KelSolaar** [comment]
Hi @whornsby,

Thanks, this is a good catch, I think it is because I used the object as a decorator instead of a context manager in the `colour.convert` definition. It does not restore properly the domain-range scale state when exiting the definition when changed internally.

> Side note: I think whoever last updated the documentation jinxed themselves when they added this warning:

No, this should be the case, the domain-range scale is/should be fixed to [0, 1] for `colour.convert`.

Can you please try 17dd6dd and let me know if it works for you, it should properly restore the state now.

**Comment by KelSolaar** [comment]
Assuming that this one is fixed!
